name: docker-dev

on:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    environment: Build
    env:
      GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
      GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: |
          npm install -g ts-node typescript
          yarn
      - name: Download BiliTools
        run: |
          mkdir temp
          ts-node tools/download.ts
      - name: Gitee Release
        run: ts-node tools/giteeRelease.ts
